use airbnb;
insert into amenities(amenity_id,name) values
(28, 'Air Conditioning'),
(14, 'Alexa'),
(22, 'Backyard'),
(29, 'Beach access'),
(3, 'Cable TV'),
(38, 'Carbon Monoxide Detector'),
(51, 'Crib'),
(13, 'Dishwasher'),
(17, 'Double Bed'),
(34, 'Dryer'),
(42, 'EV Charging Port'),
(40, 'Elevator'),
(8, 'Essentials'),
(18, 'Family/Kid Friendly'),
(46, 'Free Parking'),
(53, 'Game Console'),
(6, 'Grill'),
(0, 'Gym'),
(1, 'Hair Conditioner'),
(37, 'Hair Dryer'),
(26, 'Hangers'),
(16, 'Heating'),
(20, 'High Chair'),
(4, 'Hot Tub'),
(32, 'Hot Water'),
(10, 'Internet'),
(39, 'Iron'),
(44, 'King Bed'),
(24, 'Kitchen'),
(19, 'Laptop-Friendly Workspace'),
(41, 'Lock on Bedroom Door'),
(35, 'OTT'),
(15, 'Oven'),
(5, 'Parking'),
(47, 'Patio or Balcony'),
(31, 'Pets Allowed'),
(50, 'Private Bathroom'),
(25, 'Queen Bed'),
(33, 'Refrigirator'),
(45, 'Scenic view '),
(11, 'Self Check-In'),
(7, 'Shampoo'),
(12, 'Single Bed'),
(30, 'Smoke Detector'),
(23, 'Smoking Allowed'),
(52, 'Soap'),
(43, 'Sofa Bed'),
(9, 'Sound system'),
(49, 'Swimming pool'),
(2, 'TV'),
(21, 'Wardrobe'),
(36, 'Washer'),
(27, 'Wi-Fi'),
(48, 'stove');
